use express_way;


# 3.1 Manger-Level Transactions


# INSERT INTO Employee Table
INSERT INTO Employee (ssn, id, is_manager, start_date, hourly_rate, telephone) VALUES
  ('128484888', '3', FALSE, CURRENT_TIMESTAMP, '30', '5964949999');

# Update Employee Table
UPDATE Employee
SET hourly_rate = '28'
WHERE id = '3';

#Delete Employee Data
DELETE FROM Employee
WHERE id = '3';


#Monthly Total
SELECT SUM(total_fare)
FROM Reservations
WHERE reservation_date BETWEEN '2011/01/01' AND '2011/01/31';

#Monthly Revenue
SELECT SUM(booking_fee)
FROM Reservations
WHERE reservation_date BETWEEN '2011/01/01' AND '2011/01/31';

############################################

# List of Flights
SELECT *
FROM Flight;

############################################

#GET Customer Name
CREATE VIEW full_name AS
  SELECT
    concat(first_name, ' ', last_name),
    id
  FROM Person;

# Get Reservation From Name
SELECT *
FROM Reservations R
WHERE account_number IN
      (SELECT DISTINCT (account_number)
       FROM full_name, Customer
       WHERE full_name.`concat(first_name, ' ', last_name)` = 'Jane Smith' AND full_name.id = Customer.id);

# Get Reservation From Flights
SELECT *
FROM Reservations
WHERE reservation_number IN
      (SELECT I.reservation_number
       FROM Include I, Airline A
       WHERE I.flight_number = '111' AND I.airline_id = A.airline_id AND A.airline_id='JA' );

SELECT * FROM Flight;


############################################################


#Most Active Flight
SELECT *
FROM Flight
ORDER BY date_of_week DESC;



############################################################


# Customer that generates most revenue

#Top Customer and Total Spent
SELECT SUM(total_fare) AS 'total_spend' , C.account_number
FROM Reservations R, Customer C
WHERE R.account_number = C.account_number
GROUP BY C.account_number
ORDER BY total_spend DESC
LIMIT 1;

#Top Customer
SELECT C.account_number
FROM Reservations R, Customer C
WHERE R.account_number = C.account_number
GROUP BY C.account_number
ORDER BY SUM(booking_fee) DESC
LIMIT 1;

############################################################

# Employee that generate most revenue;
SELECT E.ssn
FROM Reservations R, Employee E
WHERE R.customer_rep_ssn = E.ssn
GROUP BY E.ssn
ORDER BY SUM(booking_fee) DESC
LIMIT 1;


###########################################################


#  Produce a summary listing of revenue generated by a particular flight, destination city, or customer

#particular flight
SELECT DISTINCT I.reservation_number, booking_fee
FROM Include I, Reservations R
WHERE I.flight_number = '111' AND I.airline_id = 'AA' AND R.reservation_number = I.reservation_number;

#destination city

SELECT DISTINCT Reservations.reservation_number , booking_fee FROM Include, Legs, Reservations
WHERE Reservations.reservation_number = Include.reservation_number AND
      Include.flight_number = Legs.flight_number AND Include.airline_id = Legs.airline_id AND Legs.to_airport IN (
  SELECT airport_id
     FROM Airport
     WHERE city = "New York"
);


#Customer
SELECT C.account_number, R.reservation_number, booking_fee
FROM Customer C, Reservations R
WHERE R.account_number = '1000001' AND C.account_number = '1000001';



###########################################################

# Produce a list of all flights for a given airport
SELECT airline_id, F.flight_number, leg_number, from_airport, to_airport, departure_time, arrival_time, seating_capacity
FROM Legs L, Flight F
WHERE L.flight_number = F.flight_number AND L.from_airport = 'JFK' AND L.airline_id = F.airline;


###########################################################


# TODO check this one??
# Produce a list of all customers who have seats reserved on a given flight
SELECT DISTINCT C.account_number
FROM Flight F, Customer C, Include I, Reservations R
WHERE F.flight_number = '111' AND I.flight_number = F.flight_number AND R.reservation_number = I.reservation_number AND R.account_number = C.account_number;

###########################################################

#Produce a list of all flights whose arrival and departure times are on-time/delayed

###########################################################



# 3.2 Customer-Representative-Level Transactions

## Record a reservation
INSERT INTO express_way.Reservations (reservation_number, account_number, reservation_date, total_fare, booking_fee, customer_rep_ssn) VALUES
  (555, '1000002', '2011-01-05 10:00:00', 5000.00, 20.00, 111111112);

## Add, Edit and Delete information for a customerCREATE TABLE Customer (
INSERT INTO Customer (id, account_number, account_create_date, credit_card, telephone, email, rating ) VALUES
  ('4', '1000004', CURRENT_TIMESTAMP, '1111222233334444', '9171111111','okok@gmail.com', '9');

UPDATE Customer
SET telephone = '3470000000'
WHERE id = '4';

DELETE FROM Customer
WHERE id = '4';

# Produce customer mailing lists
SELECT email FROM Customer
WHERE email IS NOT NULL;

# Produce a list of flight suggestions for a given customer (based on that customer's past reservations)
# idea: get the most 10 frequent flights from this cusomter's reservation history
SELECT I.flight_number, I.airline_id, COUNT(*) AS total_reserv
FROM Include I, Reservations R, Customer C
WHERE C.id=1
AND C.account_number = R.account_number
AND R.reservation_number = I.reservation_number
GROUP BY I.flight_number, I.airline_id
ORDER BY total_reserv DESC
LIMIT 10;

# 3.3 Customer-Level Transactions

# Make a one-way reservation
INSERT INTO Reservations (reservation_number, account_number, reservation_date, total_fare, booking_fee, customer_rep_ssn)
VALUES (123, '1000001', '2010-01-14 12:00:00', 500.00, 20.00, 111111111);
INSERT INTO Include (reservation_number, airline_id, flight_number, leg_number, passenger_lname, passenger_fname, dept_date, seat_number, class, meal, from_stop_num)
VALUES (123, 'AA', 111, 1, NULL, NULL, '2010-01-14', '13A', 'First', 'Fish and Chips', 1);

# Make a round-trip reservation
INSERT INTO Reservations (reservation_number, account_number, reservation_date, total_fare, booking_fee, customer_rep_ssn)
VALUES (124, '1000005', '2010-01-14 12:00:00', 500.00, 20.00, 111111111);
INSERT INTO Include (reservation_number, airline_id, flight_number, leg_number, passenger_lname, passenger_fname, dept_date, seat_number, class, meal, from_stop_num)
VALUES (124, 'JA', 111, 1, NULL, NULL, '2010-01-14', '13A', 'First', 'Fish and Chips', 1);
INSERT INTO Include (reservation_number, airline_id, flight_number, leg_number, passenger_lname, passenger_fname, dept_date, seat_number, class, meal, from_stop_num)
VALUES (124, 'AM', 1337, 1, NULL, NULL, '2010-01-14', '13A', 'First', 'Fish and Chips', 1);

# Make a multi-city reservation
INSERT INTO Reservations (reservation_number, account_number, reservation_date, total_fare, booking_fee, customer_rep_ssn)
VALUES (127, '1000003', '2010-05-14 12:00:00', 500.00, 20.00, 111111111);
INSERT INTO Include (reservation_number, airline_id, flight_number, leg_number, passenger_lname, passenger_fname, dept_date, seat_number, class, meal, from_stop_num)
VALUES (127, 'JA', 111, 1, NULL, NULL, '2010-05-14', '13A', 'First', 'Fish and Chips', 1);
INSERT INTO Include (reservation_number, airline_id, flight_number, leg_number, passenger_lname, passenger_fname, dept_date, seat_number, class, meal, from_stop_num)
VALUES (127, 'JA', 111, 2, NULL, NULL, '2010-05-14', '13A', 'First', 'Fish and Chips', 1);
INSERT INTO Include (reservation_number, airline_id, flight_number, leg_number, passenger_lname, passenger_fname, dept_date, seat_number, class, meal, from_stop_num)
VALUES (127, 'JA', 111, 3, NULL, NULL, '2010-05-14', '13A', 'First', 'Fish and Chips', 1);

# A customer's current reservations
SELECT * 
FROM Customer C, Reservations R
WHERE C.id=1 AND C.account_number = R.account_number; 

# Travel itinerary for a given reservation
SELECT L.from_airport, L.to_airport
FROM Reservations R, Include Inc,Legs L
WHERE R.reservation_number=111
AND R.reservation_number = Inc.reservation_number
AND Inc.airline_id = L.airline_id 
AND Inc.flight_number = L.flight_number
AND Inc.leg_number = L.leg_number;

# A customer's current bid on a given reverse auction

# SELECT NYOP
# FROM Auctions, Reservations R
# WHERE R.reservation_number = '111'

SELECT *
FROM Auctions
WHERE account_num = '1000001'
AND current_timestamp() < dept_date
AND Auctions.is_accepted = FALSE;


# The bid history for a given reverse auction
SELECT NYOP
FROM Auctions, Customer
WHERE Customer.account_number = '1000001' AND Auctions.account_num = Customer.account_number;



# A history of all current and past reservations a customer has made
SELECT * 
FROM Auctions A, Customer C
WHERE C.id=1 AND C.account_number = A.account_num;

# Best-Seller list of flights
SELECT I.flight_number, I.airline_id, COUNT(*) AS flight_count
FROM Include I, Reservations R
WHERE R.reservation_number = I.reservation_number
GROUP BY I.flight_number, I.airline_id
ORDER BY flight_count DESC
LIMIT 10;

# Personalized flight suggestion list	



###########################################################

SELECT F.flight_number, F.airline, L.from_airport, L.to_airport
FROM Flight F, Legs L
  WHERE (F.date_of_week & '1000000' OR F.date_of_week & '0000001')
  AND L.from_airport = "JFK" AND L.to_airport = "SFO"
  AND L.flight_number = F.flight_number AND L.airline_id = F.airline;


SELECT * FROM Legs;

#On TIme
SELECT *
FROM Legs
WHERE actual_departure_time = departure_time;

SELECT *
FROM Legs
WHERE Legs.actual_departure_time <> Legs.departure_time;




