use express_way;
# 3.1 Manger-Level Transactions
# INSERT INTO Employee Table
INSERT INTO Employee (ssn, id, is_manager, start_date, hourly_rate, telephone) VALUES
  ('128484888', '3', FALSE, CURRENT_TIMESTAMP, '30', '5964949999');

# Update Employee Table
UPDATE Employee
SET hourly_rate = '28'
WHERE id = '3';

#Delete Employee Data
DELETE FROM Employee
WHERE id = '3';

#Total Fare
SELECT SUM(total_fare)
FROM Reservations
WHERE reservation_date BETWEEN '2011/01/01' AND '2011/01/31';

#Total Booking
SELECT SUM(booking_fee)
FROM Reservations
WHERE reservation_date BETWEEN '2011/01/01' AND '2011/01/31';

############################################




#GET Customer Name
CREATE VIEW full_name AS
  SELECT
    concat(first_name, ' ', last_name),
    id
  FROM Person;

#Get Account ID from Customer Name
# SELECT DISTINCT (account_number)
# FROM full_name, Customer
# WHERE full_name.`concat(first_name, ' ' , last_name)` =  AND full_name.id = Customer.id;

# Get Reservation From Name
SELECT *
FROM Reservations R
WHERE account_number IN
      (SELECT DISTINCT (account_number)
       FROM full_name, Customer
       WHERE full_name.`concat(first_name, ' ' , last_name)` = 'Jane Smith' AND full_name.id = Customer.id);

# Get Reservation From Flights
SELECT *
FROM Reservations
WHERE reservation_number IN
      (SELECT I.reservation_number
       FROM Include I
       WHERE I.flight_number = '111');


############################################################


#Most Active Flight
SELECT *
FROM Flight
ORDER BY date_of_week DESC;



############################################################


# Customer that generates most revenue

#Top Customer and Total Spent
SELECT SUM(total_fare) AS 'total_spend' , C.account_number
FROM Reservations R, Customer C
WHERE R.account_number = C.account_number
GROUP BY C.account_number
ORDER BY total_spend DESC
LIMIT 1;

#Top Customer
SELECT C.account_number
FROM Reservations R, Customer C
WHERE R.account_number = C.account_number
GROUP BY C.account_number
ORDER BY SUM(total_fare) DESC
LIMIT 1;

############################################################

# Employee that generate most revenue;
SELECT E.ssn
FROM Reservations R, Employee E
WHERE R.customer_rep_ssn = E.ssn
GROUP BY E.ssn
ORDER BY SUM(total_fare) DESC
LIMIT 1;


###########################################################


#  Produce a summary listing of revenue generated by a particular flight, destination city, or customer
SELECT * FROM Flight;
SELECT * FROM Include;

SELECT DISTINCT I.reservation_number, total_fare
FROM Include I, Reservations R
WHERE I.flight_number = '111' AND I.airline_id = 'AA' AND R.reservation_number = I.reservation_number;


SELECT C.account_number, total_fare
FROM Customer C, Reservations R
WHERE R.account_number = '1000001' AND C.account_number = '1000001';

# TODO Destination City , Check this
SELECT * FROM Legs;

SELECT RS.reservation_number , RS.total_fare FROM Reservations RS WHERE RS.reservation_number IN
  (SELECT DISTINCT I.reservation_number
  FROM Legs L, Reservations R, Include I
  WHERE L.to_airport = 'LAX' AND L.airline_id = I.airline_id AND I.flight_number = L.flight_number
  AND R.reservation_number = I.reservation_number);

###########################################################

# Produce a list of all flights for a given airport
SELECT airline_id, F.flight_number, leg_number, from_airport, to_airport, departure_time, arrival_time, seating_capacity
FROM Legs L, Flight F
WHERE L.flight_number = F.flight_number AND L.from_airport = 'JFK' AND L.airline_id = F.airline;


###########################################################


# TODO check this one??
# Produce a list of all customers who have seats reserved on a given flight
SELECT DISTINCT C.account_number
FROM Flight F, Customer C, Include I, Reservations R
WHERE F.flight_number = '111' AND I.flight_number = F.flight_number AND R.reservation_number = I.reservation_number AND R.account_number = C.account_number;

###########################################################

#Produce a list of all flights whose arrival and departure times are on-time/delayed

###########################################################



# 3.2 Customer-Representative-Level Transactions

## Record a reservation


## Add, Edit and Delete information for a customerCREATE TABLE Customer (
INSERT INTO Customer (id, account_number, account_create_date, credit_card, telephone, email, rating ) VALUES
  ('4', '1000004', CURRENT_TIMESTAMP, '1111222233334444', '9171111111','okok@gmail.com', '9');

UPDATE Customer
SET telephone = '3470000000'
WHERE id = '4';

DELETE FROM Customer
WHERE id = '4';

# Produce customer mailing lists
SELECT email FROM Customer
WHERE email IS NOT NULL;

# Produce a list of flight suggestions for a given customer (based on that customer's past reservations)
# idea: get the most 10 frequent flights from this cusomter's reservation history
SELECT I.flight_number, I.airline_id, COUNT(*) AS total_reserv
FROM Include I, Reservations R, Customer C
WHERE C.id=1
AND C.account_number = R.account_number
AND R.reservation_number = I.reservation_number
GROUP BY I.flight_number, I.airline_id
ORDER BY total_reserv DESC
LIMIT 10;

# 3.3 Customer-Level Transactions

# One-way
-- INSERT INTO Reservations (reservation_number, account_number, reservation_date, total_fare, booking_fee, customer_rep_ssn)
-- VALUES (123, '1000001', '2011-01-05 12:00:00', 500.00, 20.00, 111111111);
-- INSERT INTO Include (reservation_number, airline_id, flight_number, leg_number, passenger_lname, passenger_fname, dept_date, seat_number, class, meal, from_stop_num)
-- VALUES (123, 'DA', 777, 1, NULL, NULL, '2016-01-14', '13A', 'First', 'Fish and Chips', 1);

# A customer's current reservations
SELECT * 
FROM Customer C, Reservations R
WHERE C.id=1 AND C.account_number = R.account_number; 

# Travel itinerary for a given reservation
SELECT L.from_airport, L.to_airport
FROM Reservations R, Include Inc,Legs L
WHERE R.reservation_number=111
AND R.reservation_number = Inc.reservation_number
AND Inc.airline_id = L.airline_id 
AND Inc.flight_number = L.flight_number
AND Inc.leg_number = L.leg_number;

# A customer's current bid on a given reverse auction

# A history of all current and past reservations a customer has made
SELECT * 
FROM Auctions A, Customer C
WHERE C.id=1 AND C.account_number = A.account_num;

# Best-Seller list of flights
SELECT I.flight_number, I.airline_id, COUNT(*) AS flight_count
FROM Include I, Reservations R
WHERE R.reservation_number = I.reservation_number
GROUP BY I.flight_number, I.airline_id
ORDER BY flight_count DESC
LIMIT 10;



